# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-08 23:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=50, verbose_name='Alias')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre(s)')),
                ('last_name', models.CharField(max_length=50, verbose_name='Apellido(s)')),
                ('phone_number', models.CharField(max_length=50, verbose_name='Telefono')),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, verbose_name='Genero')),
                ('birth_date', models.DateField(auto_now_add=True, verbose_name='Fecha de nacimiento')),
            ],
        ),
    ]
