# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-11 21:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=50, verbose_name='Alias')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre(s)')),
                ('last_name', models.CharField(max_length=50, verbose_name='Apellido(s)')),
                ('phone_number', models.CharField(max_length=50, verbose_name='Telefono')),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, verbose_name='Genero')),
                ('birth_date', models.DateField(null=True, verbose_name='Fecha de nacimiento')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Fly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_id', models.IntegerField(verbose_name='Id de reserva')),
                ('fly_number', models.IntegerField(verbose_name='Numero de vuelo')),
                ('fly_date', models.DateTimeField(verbose_name='Fecha del Vuelo')),
                ('seat_number', models.IntegerField(verbose_name='Numero de asiento')),
                ('rute', models.CharField(max_length=50, verbose_name='Ruta')),
                ('alias_from_customers', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='customers_flyes.Customer')),
            ],
        ),
    ]
